config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = %w(chinese italian japanese french belgian)

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY, message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5).to_a,
    message: "%{value} must be between 0 and 5" },
    numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    # We need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show", status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Restaurant Manager</a>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggle-icon"></span>
  </button>
  <div class="navbar-collapse collapse" id="navbarSupportedContent" style>
    <ul class="navbar-nav ml-auto">
      <li>
        <%= link_to "New Restaurant", new_restaurant_path, class: "btn btn-primary" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <h1><%= title %></h1>
      <%= simple_form_for restaurant do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :category %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <% @restaurants.each do |restaurant| %>
      <div class="card">
        <h2>
          <%= restaurant.name %>
        </h2>
        <p>
          <%= restaurant.address%>
        </p>
        <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render partial: "form", locals: { restaurant: @restaurant, title: "New Restaurant", button_text: "Create Restaurant"}%>
<div class="mt-2">
  <%= link_to "Back", restaurants_path%>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <h1>
        <%= @restaurant.name %>
      </h1>
      <p>
        <%= @restaurant.address%>
      </p>
      <p>
        <%= @restaurant.category%>
      </p>
      <%# <%= link_to "New Review", new_restaurant_review_path(@restaurant)%>
      <p><strong>Reviews</strong></p>
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit "Submit review", class: "btn btn-primary" %>
      <% end %>

      <ul class="list-group">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item">
            <%= review.content %>
            <%= review.rating%>
            </li>
        <% end %>
      </ul>
      <div class="mt-2">
        <%= link_to "Back", restaurants_path%>
      </div>
    </div>
  </div>
</div>